//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_First_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.REGISTRO_TRANSACCION_DEDUCCION = new HashSet<REGISTRO_TRANSACCION_DEDUCCION>();
            this.REGISTRO_TRANSACCION = new HashSet<REGISTRO_TRANSACCION>();
        }
    
        public int ID_EMPLEADO { get; set; }
        public string COD_EMPLEADO { get; set; }
        public string CEDULA_EMPLEADO { get; set; }
        public string NOMBRE_EMPLEADO { get; set; }
        public int ID_DEPARTAMENTO { get; set; }
        public int ID_PUESTO { get; set; }
        public double SALARIO_MENSUAL_EMPLEADO { get; set; }
        public string RESPONSABLE_AREA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_TRANSACCION_DEDUCCION> REGISTRO_TRANSACCION_DEDUCCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_TRANSACCION> REGISTRO_TRANSACCION { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual PUESTO PUESTO { get; set; }
    }
}
