
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 08/20/2021 17:15:31
-- Generated from EDMX file: C:\Users\Tarde\Desktop\Asata Saúl Otero Melchor\curso_net\Model First 2\Model First 2\Model1.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [ModelFirst2];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------


-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------


-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'EMPLEADOSet'
CREATE TABLE [dbo].[EMPLEADOSet] (
    [ID_EMPLEADO] int IDENTITY(1,1) NOT NULL,
    [COD_EMPLEADO] nvarchar(max)  NOT NULL,
    [CEDULA_EMPLEADO] nvarchar(max)  NOT NULL,
    [NOMBRE_EMPLEADO] nvarchar(max)  NOT NULL,
    [ID_DEPARTAMENTO] int  NOT NULL,
    [ID_PUESTO] int  NOT NULL,
    [SALARIO_MENSUAL_EMPLEADO] float  NOT NULL,
    [RESPONSABLE_AREA] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'PUESTOSet'
CREATE TABLE [dbo].[PUESTOSet] (
    [ID_PUESTO] int IDENTITY(1,1) NOT NULL,
    [NOMBRE_PUESTO] nvarchar(max)  NOT NULL,
    [ID_NIVEL_RIESGO] int  NOT NULL,
    [NIVEL_SALARIO_MIN] int  NOT NULL,
    [NIVEL_SALARIO_MAX] int  NOT NULL
);
GO

-- Creating table 'NIVEL_RIESGOSet'
CREATE TABLE [dbo].[NIVEL_RIESGOSet] (
    [ID_NIVEL_RIESGO] int IDENTITY(1,1) NOT NULL,
    [TIPO_RIESGO] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'DEPARTAMENTOSet'
CREATE TABLE [dbo].[DEPARTAMENTOSet] (
    [ID_DEPARTAMENTO] int IDENTITY(1,1) NOT NULL,
    [NOMBRE_DEPARTAMENTO] nvarchar(max)  NOT NULL,
    [UBICACION_FISICA_DEPARTAMENTO] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'REGISTRO_TRANSACCIONSet'
CREATE TABLE [dbo].[REGISTRO_TRANSACCIONSet] (
    [ID_TRANSACCION_INGRESO] int IDENTITY(1,1) NOT NULL,
    [ID_EMPLEADO] int  NOT NULL,
    [ID_TIPO_INGRESO] int  NOT NULL,
    [FECHA] datetime  NOT NULL,
    [MONTO] float  NOT NULL
);
GO

-- Creating table 'TIPO_DE_INGRESOSet'
CREATE TABLE [dbo].[TIPO_DE_INGRESOSet] (
    [ID_TIPO_INGRESO] int IDENTITY(1,1) NOT NULL,
    [NOMBRE_TIPO_INGRESO] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'REGISTRO_TRANSACCION_DEDUCCIONSet'
CREATE TABLE [dbo].[REGISTRO_TRANSACCION_DEDUCCIONSet] (
    [ID_TRANSACCION_DEDUCCION] int IDENTITY(1,1) NOT NULL,
    [ID_EMPLEADO] int  NOT NULL,
    [ID_TIPO_DEDUCCION] int  NOT NULL,
    [FECHA] datetime  NOT NULL,
    [MONTO] float  NOT NULL
);
GO

-- Creating table 'TIPO_DE_DEDUCCIONSet'
CREATE TABLE [dbo].[TIPO_DE_DEDUCCIONSet] (
    [ID_TIPO_DEDUCCION] int IDENTITY(1,1) NOT NULL,
    [NOMBRE_TIPO_DEDUCCION] nvarchar(max)  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [ID_EMPLEADO] in table 'EMPLEADOSet'
ALTER TABLE [dbo].[EMPLEADOSet]
ADD CONSTRAINT [PK_EMPLEADOSet]
    PRIMARY KEY CLUSTERED ([ID_EMPLEADO] ASC);
GO

-- Creating primary key on [ID_PUESTO] in table 'PUESTOSet'
ALTER TABLE [dbo].[PUESTOSet]
ADD CONSTRAINT [PK_PUESTOSet]
    PRIMARY KEY CLUSTERED ([ID_PUESTO] ASC);
GO

-- Creating primary key on [ID_NIVEL_RIESGO] in table 'NIVEL_RIESGOSet'
ALTER TABLE [dbo].[NIVEL_RIESGOSet]
ADD CONSTRAINT [PK_NIVEL_RIESGOSet]
    PRIMARY KEY CLUSTERED ([ID_NIVEL_RIESGO] ASC);
GO

-- Creating primary key on [ID_DEPARTAMENTO] in table 'DEPARTAMENTOSet'
ALTER TABLE [dbo].[DEPARTAMENTOSet]
ADD CONSTRAINT [PK_DEPARTAMENTOSet]
    PRIMARY KEY CLUSTERED ([ID_DEPARTAMENTO] ASC);
GO

-- Creating primary key on [ID_TRANSACCION_INGRESO] in table 'REGISTRO_TRANSACCIONSet'
ALTER TABLE [dbo].[REGISTRO_TRANSACCIONSet]
ADD CONSTRAINT [PK_REGISTRO_TRANSACCIONSet]
    PRIMARY KEY CLUSTERED ([ID_TRANSACCION_INGRESO] ASC);
GO

-- Creating primary key on [ID_TIPO_INGRESO] in table 'TIPO_DE_INGRESOSet'
ALTER TABLE [dbo].[TIPO_DE_INGRESOSet]
ADD CONSTRAINT [PK_TIPO_DE_INGRESOSet]
    PRIMARY KEY CLUSTERED ([ID_TIPO_INGRESO] ASC);
GO

-- Creating primary key on [ID_TRANSACCION_DEDUCCION] in table 'REGISTRO_TRANSACCION_DEDUCCIONSet'
ALTER TABLE [dbo].[REGISTRO_TRANSACCION_DEDUCCIONSet]
ADD CONSTRAINT [PK_REGISTRO_TRANSACCION_DEDUCCIONSet]
    PRIMARY KEY CLUSTERED ([ID_TRANSACCION_DEDUCCION] ASC);
GO

-- Creating primary key on [ID_TIPO_DEDUCCION] in table 'TIPO_DE_DEDUCCIONSet'
ALTER TABLE [dbo].[TIPO_DE_DEDUCCIONSet]
ADD CONSTRAINT [PK_TIPO_DE_DEDUCCIONSet]
    PRIMARY KEY CLUSTERED ([ID_TIPO_DEDUCCION] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [ID_TIPO_DEDUCCION] in table 'REGISTRO_TRANSACCION_DEDUCCIONSet'
ALTER TABLE [dbo].[REGISTRO_TRANSACCION_DEDUCCIONSet]
ADD CONSTRAINT [FK_TIPO_DE_DEDUCCIONREGISTRO_TRANSACCION_DEDUCCION]
    FOREIGN KEY ([ID_TIPO_DEDUCCION])
    REFERENCES [dbo].[TIPO_DE_DEDUCCIONSet]
        ([ID_TIPO_DEDUCCION])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TIPO_DE_DEDUCCIONREGISTRO_TRANSACCION_DEDUCCION'
CREATE INDEX [IX_FK_TIPO_DE_DEDUCCIONREGISTRO_TRANSACCION_DEDUCCION]
ON [dbo].[REGISTRO_TRANSACCION_DEDUCCIONSet]
    ([ID_TIPO_DEDUCCION]);
GO

-- Creating foreign key on [ID_EMPLEADO] in table 'REGISTRO_TRANSACCION_DEDUCCIONSet'
ALTER TABLE [dbo].[REGISTRO_TRANSACCION_DEDUCCIONSet]
ADD CONSTRAINT [FK_EMPLEADOREGISTRO_TRANSACCION_DEDUCCION]
    FOREIGN KEY ([ID_EMPLEADO])
    REFERENCES [dbo].[EMPLEADOSet]
        ([ID_EMPLEADO])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPLEADOREGISTRO_TRANSACCION_DEDUCCION'
CREATE INDEX [IX_FK_EMPLEADOREGISTRO_TRANSACCION_DEDUCCION]
ON [dbo].[REGISTRO_TRANSACCION_DEDUCCIONSet]
    ([ID_EMPLEADO]);
GO

-- Creating foreign key on [ID_TIPO_INGRESO] in table 'REGISTRO_TRANSACCIONSet'
ALTER TABLE [dbo].[REGISTRO_TRANSACCIONSet]
ADD CONSTRAINT [FK_TIPO_DE_INGRESOREGISTRO_TRANSACCION]
    FOREIGN KEY ([ID_TIPO_INGRESO])
    REFERENCES [dbo].[TIPO_DE_INGRESOSet]
        ([ID_TIPO_INGRESO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TIPO_DE_INGRESOREGISTRO_TRANSACCION'
CREATE INDEX [IX_FK_TIPO_DE_INGRESOREGISTRO_TRANSACCION]
ON [dbo].[REGISTRO_TRANSACCIONSet]
    ([ID_TIPO_INGRESO]);
GO

-- Creating foreign key on [ID_EMPLEADO] in table 'REGISTRO_TRANSACCIONSet'
ALTER TABLE [dbo].[REGISTRO_TRANSACCIONSet]
ADD CONSTRAINT [FK_EMPLEADOREGISTRO_TRANSACCION]
    FOREIGN KEY ([ID_EMPLEADO])
    REFERENCES [dbo].[EMPLEADOSet]
        ([ID_EMPLEADO])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPLEADOREGISTRO_TRANSACCION'
CREATE INDEX [IX_FK_EMPLEADOREGISTRO_TRANSACCION]
ON [dbo].[REGISTRO_TRANSACCIONSet]
    ([ID_EMPLEADO]);
GO

-- Creating foreign key on [ID_DEPARTAMENTO] in table 'EMPLEADOSet'
ALTER TABLE [dbo].[EMPLEADOSet]
ADD CONSTRAINT [FK_DEPARTAMENTOEMPLEADO]
    FOREIGN KEY ([ID_DEPARTAMENTO])
    REFERENCES [dbo].[DEPARTAMENTOSet]
        ([ID_DEPARTAMENTO])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DEPARTAMENTOEMPLEADO'
CREATE INDEX [IX_FK_DEPARTAMENTOEMPLEADO]
ON [dbo].[EMPLEADOSet]
    ([ID_DEPARTAMENTO]);
GO

-- Creating foreign key on [ID_NIVEL_RIESGO] in table 'PUESTOSet'
ALTER TABLE [dbo].[PUESTOSet]
ADD CONSTRAINT [FK_NIVEL_RIESGOPUESTO]
    FOREIGN KEY ([ID_NIVEL_RIESGO])
    REFERENCES [dbo].[NIVEL_RIESGOSet]
        ([ID_NIVEL_RIESGO])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_NIVEL_RIESGOPUESTO'
CREATE INDEX [IX_FK_NIVEL_RIESGOPUESTO]
ON [dbo].[PUESTOSet]
    ([ID_NIVEL_RIESGO]);
GO

-- Creating foreign key on [ID_PUESTO] in table 'EMPLEADOSet'
ALTER TABLE [dbo].[EMPLEADOSet]
ADD CONSTRAINT [FK_PUESTOEMPLEADO]
    FOREIGN KEY ([ID_PUESTO])
    REFERENCES [dbo].[PUESTOSet]
        ([ID_PUESTO])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PUESTOEMPLEADO'
CREATE INDEX [IX_FK_PUESTOEMPLEADO]
ON [dbo].[EMPLEADOSet]
    ([ID_PUESTO]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------