//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_First_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPLEADO> EMPLEADOSet { get; set; }
        public virtual DbSet<PUESTO> PUESTOSet { get; set; }
        public virtual DbSet<NIVEL_RIESGO> NIVEL_RIESGOSet { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOSet { get; set; }
        public virtual DbSet<REGISTRO_TRANSACCION> REGISTRO_TRANSACCIONSet { get; set; }
        public virtual DbSet<TIPO_DE_INGRESO> TIPO_DE_INGRESOSet { get; set; }
        public virtual DbSet<REGISTRO_TRANSACCION_DEDUCCION> REGISTRO_TRANSACCION_DEDUCCIONSet { get; set; }
        public virtual DbSet<TIPO_DE_DEDUCCION> TIPO_DE_DEDUCCIONSet { get; set; }
    }
}
