#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRUEBA_PRÁCTICA_UNIDAD_UF1846
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EXAMEN")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::PRUEBA_PRÁCTICA_UNIDAD_UF1846.Properties.Settings.Default.EXAMENConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AñadirProducto")]
		public int sp_AñadirProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMPROD", DbType="VarChar(20)")] string nOMPROD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO", DbType="Decimal(20,2)")] System.Nullable<decimal> pRECIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STOCK", DbType="Int")] System.Nullable<int> sTOCK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMPROD, pRECIO, sTOCK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ModificaProducto")]
		public int sp_ModificaProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMPROD", DbType="VarChar(20)")] string nOMPROD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO", DbType="Decimal(20,2)")] System.Nullable<decimal> pRECIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STOCK", DbType="Int")] System.Nullable<int> sTOCK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMPROD, pRECIO, sTOCK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarProducto")]
		public int sp_EliminarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMPROD", DbType="VarChar(20)")] string nOMPROD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMPROD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BuscarCliente")]
		public ISingleResult<sp_BuscarClienteResult> sp_BuscarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMPROD", DbType="VarChar(20)")] string nOMPROD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMPROD);
			return ((ISingleResult<sp_BuscarClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarCombo")]
		public ISingleResult<listarComboResult> listarCombo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarComboResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarTodos")]
		public ISingleResult<ListarTodosResult> ListarTodos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarTodosResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_BuscarClienteResult
	{
		
		private string _NombreProducto;
		
		private System.Nullable<decimal> _PrecioUnidad;
		
		private System.Nullable<int> _UnidadStock;
		
		public sp_BuscarClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioUnidad", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioUnidad
		{
			get
			{
				return this._PrecioUnidad;
			}
			set
			{
				if ((this._PrecioUnidad != value))
				{
					this._PrecioUnidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadStock", DbType="Int")]
		public System.Nullable<int> UnidadStock
		{
			get
			{
				return this._UnidadStock;
			}
			set
			{
				if ((this._UnidadStock != value))
				{
					this._UnidadStock = value;
				}
			}
		}
	}
	
	public partial class listarComboResult
	{
		
		private string _NombreProducto;
		
		public listarComboResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
	}
	
	public partial class ListarTodosResult
	{
		
		private string _NombreProducto;
		
		private System.Nullable<decimal> _PrecioUnidad;
		
		private System.Nullable<int> _UnidadStock;
		
		public ListarTodosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioUnidad", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioUnidad
		{
			get
			{
				return this._PrecioUnidad;
			}
			set
			{
				if ((this._PrecioUnidad != value))
				{
					this._PrecioUnidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadStock", DbType="Int")]
		public System.Nullable<int> UnidadStock
		{
			get
			{
				return this._UnidadStock;
			}
			set
			{
				if ((this._UnidadStock != value))
				{
					this._UnidadStock = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
