//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repaso_Agosto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public string DNI { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
    }
}
