#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenParcial25_08Saúl
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EXAMEN")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertPRODUCTOS(PRODUCTOS instance);
    partial void UpdatePRODUCTOS(PRODUCTOS instance);
    partial void DeletePRODUCTOS(PRODUCTOS instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ExamenParcial25_08Saúl.Properties.Settings.Default.EXAMENConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PRODUCTOS> PRODUCTOS
		{
			get
			{
				return this.GetTable<PRODUCTOS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTOS")]
	public partial class PRODUCTOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NombreProducto;
		
		private System.Nullable<decimal> _PrecioUnidad;
		
		private System.Nullable<int> _UnidadStock;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNombreProductoChanging(string value);
    partial void OnNombreProductoChanged();
    partial void OnPrecioUnidadChanging(System.Nullable<decimal> value);
    partial void OnPrecioUnidadChanged();
    partial void OnUnidadStockChanging(System.Nullable<int> value);
    partial void OnUnidadStockChanged();
    #endregion
		
		public PRODUCTOS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this.OnNombreProductoChanging(value);
					this.SendPropertyChanging();
					this._NombreProducto = value;
					this.SendPropertyChanged("NombreProducto");
					this.OnNombreProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioUnidad", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioUnidad
		{
			get
			{
				return this._PrecioUnidad;
			}
			set
			{
				if ((this._PrecioUnidad != value))
				{
					this.OnPrecioUnidadChanging(value);
					this.SendPropertyChanging();
					this._PrecioUnidad = value;
					this.SendPropertyChanged("PrecioUnidad");
					this.OnPrecioUnidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadStock", DbType="Int")]
		public System.Nullable<int> UnidadStock
		{
			get
			{
				return this._UnidadStock;
			}
			set
			{
				if ((this._UnidadStock != value))
				{
					this.OnUnidadStockChanging(value);
					this.SendPropertyChanging();
					this._UnidadStock = value;
					this.SendPropertyChanged("UnidadStock");
					this.OnUnidadStockChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
