--CREAR TABLAS
CREATE TABLE CLIENTE(
IDCLIENTE varchar(5) PRIMARY KEY NOT NULL,
APELLIDOS varchar(30) NULL,
NOMBRE varchar(30) NULL
);

CREATE TABLE CUENTA (
IDCLIENTE	varchar(5) NULL,
IDCUENTA varchar(5) PRIMARY KEY NOT NULL,
SALDO float NULL,
DIVISA varchar(20) NULL,
CONSTRAINT  FK_CuentaCliente FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE MOVIMIENTO(
IDCUENTA varchar(5) NULL,
IDMOVIMIENTO varchar(5) PRIMARY KEY NOT NULL,
TIPO varchar(20) NULL,
MONTO float NULL,
FECHA date NULL
CONSTRAINT  FK_MovimientoCuenta FOREIGN KEY (IDCUENTA) REFERENCES CUENTA(IDCUENTA)
);

--AÑADIR REGISTROS
INSERT INTO CLIENTE(IDCLIENTE,APELLIDOS,NOMBRE)
VALUES(7,'ROMUALDO','CRISTIANO')

INSERT INTO CLIENTE(IDCLIENTE,APELLIDOS,NOMBRE)
VALUES(9,'IGLESIAS','GUILLER')

INSERT INTO CUENTA(IDCLIENTE,IDCUENTA,SALDO,DIVISA)
VALUES(9,3,20000,'RUBLOS')

INSERT INTO CUENTA(IDCLIENTE,IDCUENTA,SALDO,DIVISA)
VALUES(7,1,1000000,'LEURO')

INSERT INTO MOVIMIENTO(IDCUENTA,IDMOVIMIENTO,TIPO,MONTO,FECHA)
VALUES(1,77,'RETIRAR',80000,'20151114')

INSERT INTO MOVIMIENTO(IDCUENTA,IDMOVIMIENTO,TIPO,MONTO,FECHA)
VALUES(3,6,'RETIRAR',180,'20191004')
--CONSULTAS

	--1 CONSULTAR LAS CUENTAS DE LOS CLIENTES CUYO APELLIDO EMPIECE POR A
SELECT *
FROM CUENTA INNER JOIN  CLIENTE
ON CUENTA.IDCLIENTE=CLIENTE.IDCLIENTE
WHERE APELLIDOS LIKE 'A%'

	--2.CONSULTAR TODOS LOS MOVIMINETOS DE LAS CUENTAS EN DIVISA LEURO DEL CLIENTE
	--CUYOS APELLIDOS ES ROMUALDO
SELECT *
FROM MOVIMIENTO INNER JOIN CUENTA
ON MOVIMIENTO.IDCUENTA=CUENTA.IDCUENTA
INNER JOIN CLIENTE
ON cliente.IDCLIENTE=CUENTA.IDCLIENTE
WHERE CLIENTE.APELLIDOS='ROMUALDO';

	--3 CONSULTAR TODOS LOS MOVIMIENTO DE LAS CUENTAS DEL CLIENTE ROMUALDO EN LEUROS
	--(AUNQUE TENGA CUENTAS EN OTRAS DIVISAS) ORDENADOS POR EL NUMERO DE CUENTA
SELECT *
FROM MOVIMIENTO INNER JOIN CUENTA
ON MOVIMIENTO.IDCUENTA=CUENTA.IDCUENTA
INNER JOIN CLIENTE
ON cliente.IDCLIENTE=CUENTA.IDCLIENTE
WHERE CLIENTE.APELLIDOS='ROMUALDO' AND CUENTA.DIVISA LIKE'LEURO'
ORDER BY CUENTA.IDCUENTA

	--4 CONSULTAR TODOS LOS MOVIMIENTOS DE ROMUALDO Y LOS DE IGLESIAS
SELECT *
FROM MOVIMIENTO INNER JOIN CUENTA
ON MOVIMIENTO.IDCUENTA=CUENTA.IDCUENTA
INNER JOIN CLIENTE
ON cliente.IDCLIENTE=CUENTA.IDCLIENTE
WHERE CLIENTE.APELLIDOS LIKE 'ROMUALDO' or CLIENTE.APELLIDOS LIKE'IGLESIAS'

--PROCEDIMIENTOS ALMACENADOS

	--5 PROCEDIMIENTO PARA AÑADIR CLIENTES
CREATE PROCEDURE insertarcliente
@idcliente varchar(5),
@apellido varchar(30),
@nombre varchar(30)
AS
INSERT INTO Cliente(IDCLIENTE,APELLIDOS,NOMBRE)
VALUES(@idcliente,@apellido,@nombre)
GO
EXEC insertarcliente 1980,'HALCÓN','ANTONIO'

	--6 CREA UN PROCEDIMIENTO ALMACENADO QUE MUESTRE TODA LA INFORMACION A PARTIR DE UN IDCUENTA INTRODUCIDA
CREATE PROCEDURE buscarIDCuenta
@IDCuenta varchar(5)
AS
SELECT * FROM CUENTA WHERE IDCUENTA LIKE '%'+@IDCuenta+'%'

EXEC buscarIDCuenta 1


	--7 CREA UN PROCEDIMIENTO ALMACENADO PARA ELIMINAR UN CLIENTE
CREATE PROCEDURE EliminarCliente
@IDCliente varchar(5)
AS
DELETE FROM CLIENTE WHERE @IDCliente=IDCLIENTE

EXEC EliminarCliente '7'

--9 CREA UN PROCEDIMIENTO ALMACENADO PARA MODIFICAR UN CLIENTE

CREATE PROCEDURE Modificarcliente
@idcliente varchar(5),
@apellido varchar(30),
@nombre varchar(30)
AS
UPDATE CLIENTE
SET IDCLIENTE=@idcliente,APELLIDOS=@apellido,NOMBRE=@nombre
WHERE IDCLIENTE=@idcliente

EXEC Modificarcliente 1980,'MOGOLLÓN','ANTONIO'

--listar
--LISTAR
CREATE PROCEDURE ListarClientes
AS
SELECT * FROM CLIENTE;

EXEC ListarClientes

-- PROCEDIMIENTOS BUSCAR
CREATE PROCEDURE buscarIDCliente
@IDCliente varchar(5)
AS
SELECT * FROM CLIENTE WHERE IDCLIENTE LIKE '%'+@IDCliente+'%'

EXEC buscarIDCliente 7

CREATE PROCEDURE buscarNombre
@Nombre varchar(30)
AS
SELECT * FROM CLIENTE WHERE NOMBRE LIKE '%'+@Nombre+'%'
EXEC buscarNombre 'PELAYO'

CREATE PROCEDURE buscarApellido
@Apellido varchar(30)
AS
SELECT * FROM CLIENTE WHERE APELLIDOS LIKE '%'+@Apellido+'%'
GO
EXEC buscarApellido 'ROMUALDO'