CREATE TABLE CLIENTE(
IDCLIENTE varchar(5) PRIMARY KEY NOT NULL,
APELLIDOS varchar(30) NULL,
NOMBRE varchar(30) NULL
);

CREATE TABLE CUENTA (
IDCLIENTE	varchar(5) NULL,
IDCUENTA varchar(5) PRIMARY KEY NOT NULL,
SALDO float NULL,
DIVISA varchar(20) NULL,
CONSTRAINT  FK_CuentaCliente FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE MOVIMIENTO(
IDCUENTA varchar(5) NULL,
IDMOVIMIENTO varchar(5) PRIMARY KEY NOT NULL,
TIPO varchar(20) NULL,
MONTO float NULL,
FECHA date NULL
CONSTRAINT  FK_MovimientoCuenta FOREIGN KEY (IDCUENTA) REFERENCES CUENTA(IDCUENTA)
);

